apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reflow-gateway.fullname" . }}
  labels:
    {{- include "reflow-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
